#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

### Autostart
nm-applet &
compfy --daemon
xfce4-power-manager &
mpd --no-daemon "$HOME"/.config/mpd/mpd.conf &
mpDris2 -c "$HOME"/.config/mpDris2/mpDris2.conf &
blueman-applet &
$HOME/.config/herbstluftwm/herbstScripts/panel.sh &

# Keybindings
. "$HOME"/.config/herbstluftwm/keyBinds 
# Theme
. "$HOME"/.config/herbstluftwm/theme
# Rules
. "$HOME"/.config/herbstluftwm/winRules
# Monitors
. "$HOME"/.config/herbstluftwm/monitors

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done
hc set tree_style '╾│ ├└╼─┐'


hc split vertical 0.6; hc remove
